get http://localhost:8080/movies


###
@id=tt0111161
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InRlc3RpbmdAaG90bWFpbC5jb20iLCJGaXJzdE5hbWUiOiJURVNUSU5HIiwiTGFzdE5hbWUiOiJhZHNmIiwiUm9sZSI6IkFETUlOIiwiVXNlcklkIjoiNjk3M2Q0ZWEwNTI3YWExYzVjNDZlMzQ2IiwiaXNzIjoiU3RyZWFtIiwiZXhwIjoxNzY5Mjg1MjUzLCJpYXQiOjE3NjkxOTg4NTN9.igf8krs42F6eNgBagiNH49wHHki7v4drvgY0AK0T2QI
get http://localhost:8080/movie/{{id}}
Authorization: Bearer {{access_token}}


###
post http://localhost:8080/addmovie
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "imdb_id": "tt0102034",
    "title": "Highlander 2: The Quickening",
    "poster_path": "https://image.tmdb.org/t/p/original/gFPIgpwtnsiq6AG5HlgOzK1TNke.jpg",
    "youtube_id": "pRgJVvoihCQ",
    "genre": [
        {
            "genre_id": 6,
            "genre_name": "Sci-fi"
        },
        {
            "genre_id": 4,
            "genre_name": "Fantasy"
        }
    ],
    "admin_review": "i really hated this movie",
    "ranking": {
        "ranking_value": 4,
        "ranking_name": "bad"
    }
}

###
post http://localhost:8080/register
Content-Type: application/json

{
  "first_name": "TESTING",
  "last_name": "adsf",
  "email": "testing@hotmail.com",
  "password": "Password112",
  "role": "ADMIN",
  "token": "",
  "refresh_token": "",
  "favourite_genres": [
    {
      "genre_id": 1,
      "genre_name": "Comedy"
    },
    {
      "genre_id": 5,
      "genre_name": "Thriller"
    },
    {
      "genre_id": 6,
      "genre_name": "Sci-Fi"
    }
  ]
}


###
post http://localhost:8080/login
Content-Type: application/json

{
  "email": "testing@hotmail.com",
  "password": "Password112"
}


###
get  http://localhost:8080/recommendedmovies
Authorization: Bearer {{access_token}}

@id=tt0111161
###
PATCH http://localhost:8080/updatereview/{{id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "admin_review": "bad movie, not recommended"
}


